INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (841,"A0",1189);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (594,"A1",841);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (420,"A2",594);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (297,"A3",420);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (210,"A4",297);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (148,"A5",210);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (105,"A6",148);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (74,"A7",105);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (52,"A8",74);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (8.5,"Letter",11);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (11,"Tabloid",17);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (8.5,"Legal",14);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (229,"C4",324);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (162,"C5",229);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (114,"C6",162);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (110,"DL",220);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (7.25,"Executive",10.5);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (8.5,"Folio",13);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (17,"Ledger/Tabloid",11);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (4,"Postcard",6);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (8,"Square formats 1",8);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (12,"Square formats",12);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (8.5,"Brochure Letter size folded into thirds",11);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (8.5,"Brochure Legal size folded into thirds",14);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (11,"Brochure Tabloid size folded into halves or thirds",17);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (5.5,"Booklet Half Letter size ",8.5);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (6,"Booklet Formats 1",9);
INSERT INTO `paper_format`(`length`, `name`, `width`) VALUES (7,"Booklet Formats 2",10);