INSERT INTO `job_type`(`name`, `category` ) VALUES ("Brochures", 0);
INSERT INTO `job_type`(`name`, `category`) VALUES ("Flyers", 0);
INSERT INTO `job_type`(`name`, `category`) VALUES ("Catalogs", 2);
INSERT INTO `job_type`(`name`, `category`) VALUES ("Magazines", 2);
INSERT INTO `job_type`(`name`, `category`) VALUES ("Newspapers", 2);
INSERT INTO `job_type`(`name`, `category`) VALUES ("Posters", 0);
INSERT INTO `job_type`(`name`, `category`) VALUES ("Book", 2);
INSERT INTO `job_type`(`name`, `category`) VALUES ("Envelope", 0);
INSERT INTO `job_type`(`name`, `category`) VALUES ("Cards", 0);
INSERT INTO `job_type`(`name`, `category`) VALUES ("Ticket", 2);
INSERT INTO `job_type`(`name`, `category`) VALUES ("Calendar", 0);
INSERT INTO `job_type`(`name`, `category`) VALUES ("Funeral program", 2);
INSERT INTO `job_type`(`name`, `category`) VALUES ("Posters Text Documents", 0);
INSERT INTO `job_type`(`name`, `category`) VALUES ("Driving licence application form", 1);
