INSERT INTO `job_type`(`name`) VALUES ("Brochures");
INSERT INTO `job_type`(`name`) VALUES ("Flyers");
INSERT INTO `job_type`(`name`) VALUES ("Catalogs");
INSERT INTO `job_type`(`name`) VALUES ("Magazines");
INSERT INTO `job_type`(`name`) VALUES ("Newspapers");
INSERT INTO `job_type`(`name`) VALUES ("Posters");
INSERT INTO `job_type`(`name`) VALUES ("Banners");
INSERT INTO `job_type`(`name`) VALUES ("Book");
INSERT INTO `job_type`(`name`) VALUES ("Envelope");
INSERT INTO `job_type`(`name`) VALUES ("Cards");
INSERT INTO `job_type`(`name`) VALUES ("Ticket");
INSERT INTO `job_type`(`name`) VALUES ("Calendar");
INSERT INTO `job_type`(`name`) VALUES ("Funeral program");
INSERT INTO `job_type`(`name`) VALUES ("Posters Text Documents");
