

INSERT INTO `role` ( `created_at`, `description`, `name`) VALUES
( NULL, 'register a new user','ROLE_CREATE_USER'),
( NULL, 'EDIT a new user','ROLE_EDIT_USER'),
( NULL, 'disactive a new user','ROLE_DESACTIVATE_USER'),
( NULL, 'ADD  a new GROUP','ROLE_ADD_GROUP'),
( NULL, 'EDIT  a  GROUP','ROLE_EDIT_GROUP'),
( NULL, 'admin  a  GROUP','ROLE_ADMIN'),
( NULL, 'REGISTER  a  PATIENT','ROLE_REGISTER_PATIENT'),
( NULL, 'VIEW  a  PATIENT','ROLE_VIEW_PATIENT'),
( NULL, 'EDIT  a  PATIENT','ROLE_EDIT_PATIENT'),
( NULL, 'VIEW  a  PATIENT HISTORY','ROLE_VIEW_PATIENT_HISTORY'),
( NULL, 'ROLE CASHIER','ROLE_CASHIER'),
( NULL, 'ROLE LIST SERVICES','ROLE_LIST_SERVICES'),
( NULL, 'CREATE A SERVICE','ROLE_CREATE_SERVICE'),
( NULL, 'EDIT A SERVICE','ROLE_EDIT_SERVICE'),
( NULL, 'VIEW A SERVICE','ROLE_VIEW_SERVICE'),
( NULL, 'VIEW A SERVICE HISTORY','ROLE_VIEW_SERVICE_HISTORY'),
( NULL, 'ASSIGN A SERVICE ','ROLE_ASIGN_SERVICE'),
( NULL, 'DISABLE A SERVICE ','ROLE_DISABLE_SERVICE'),
( NULL, 'VIEW PAYMENT ','ROLE_VIEW_PAYMENT'),
( NULL, 'CREATE PAYMENT ','ROLE_CREATE_PAYMENT'),
( NULL, 'RECEIVE PAYMENT ','ROLE_RECEIVE_PAYMENT'),
( NULL, 'PRINT PAYMENT RECEIPT ','ROLE_PRINT_PAYMENT_RECEIPT'),
( NULL, 'ROLE INVENTORY ','ROLE_VIEW_STORE'),
( NULL, 'ROLE REGISTER MEDICINE ','ROLE_REGISTER_MEDICINE'),
( NULL, 'ROLE VIEW MEDICINE ','ROLE_VIEW_MEDICINE'),
( NULL, 'ROLE EDIT MEDICINE ','ROLE_EDIT_MEDICINE'),
( NULL, 'ROLE ADD MEDICINE ','ROLE_ADD_MEDICINE'),
( NULL, 'ROLE HISTORY MEDICINE ','ROLE_VIEW_MEDICINE_HISTORY'),
( NULL, 'ROLE TRANSFER MEDICINE ','ROLE_TRANSFER_MEDICINE'),
( NULL, 'ROLE SEARCH MEDICINE ','ROLE_SEARCH_MEDICINE'),
( NULL, 'ROLE PHAMARCY ','ROLE_PHAMARCY'),
( NULL, 'ROLE ADD_TO_CARTE ','ROLE_ADD-TO_CARTE'),
( NULL, 'ROLE PHAMARCY  CHECKOUT','ROLE_PHAMARCY_CHECKOUT'),
( NULL, 'ROLE PHAMARCY  CHECKOUT','ROLE_PHAMARCY_REQUEST_MEDICINE'),
( NULL, 'ROLE INVOICE  MANAGEMENT','ROLE_INVOICE_MANAGEMENT'),
( NULL, 'ROLE STAFF  MANAGEMENT','ROLE_STAFF_MANAGEMENT'),
( NULL, 'ROLE STAFF  PAYROLL','ROLE_STAFF_PAYROLL'),
( NULL, 'ROLE STATISTIC  MANAGEMENT','ROLE_STATISTIC_MANAGEMENT');








































(NULL, 'register a new staff','ROLE_REGISTER_STAFF'),




